name: main

# Define the event that triggers the workflow
on: push
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest  # Specify the environment to run the job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7  # Checkout the repository's code

      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
